name: Create tag release
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+-beta[0-9]+'

permissions:
  actions: write
  contents: write

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true

jobs:
  versioning:
    uses: ./.github/workflows/01-versioning.yml

  build-nuget:
    needs: versioning
    uses: ./.github/workflows/02-build-nuget.yml
    with:
      tag: ${{ needs.versioning.outputs.tag }}

  # build-vsix:
  #   needs: versioning
  #   uses: ./.github/workflows/03-build-vsix.yml

  # publish-nuget:
  #   needs: build-nuget #, build-vsix
  #   uses: ./.github/workflows/04-publish-nuget.yml
  #   with:
  #     tag: ${{ needs.versioning.outputs.tag }}
  #   secrets:
  #     nuget-api-key: ${{ secrets.NUGET_API_KEY }}

  publish-nuget:
    needs: build-nuget
    runs-on: ubuntu-latest
    steps:
    - uses: actions/cache/restore@v4
      with:
        path: nupkg
        key: cache-${{ github.sha }}
        enableCrossOsArchive: true
    - run: echo "PACKAGE=$(find . -name "EcoCode.${{ needs.versioning.outputs.tag }}.nupkg" | head -n 1)" >> $GITHUB_ENV
    - run: dotnet nuget push ${{ env.PACKAGE }} -k "${{ secrets.NUGET_API_KEY }}" -s https://api.nuget.org/v3/index.json

  # publish-vsix:
  #   needs: [versioning, build-nuget, build-vsix]
  #   uses: ./.github/workflows/05-publish-vsix.yml
  #   with:
  #     tag: ${{ needs.versioning.outputs.tag }}
  #     version: ${{ needs.versioning.outputs.version }}
  #   secrets:
  #     vsmarketplace-api-key: ${{ secrets.VSMARKETPLACE_API_KEY }}

  create-release:
    # needs: [publish-nuget, publish-vsix]
    needs: publish-nuget
    uses: ./.github/workflows/06-create-release.yml
    with:
      tag: ${{ needs.versioning.outputs.tag }}
      version: ${{ needs.versioning.outputs.version }}
